title: Story Notes - Technical Recipes
author: Tony Hirst
copyright: "2022" 
only_build_toc_files: true

repository:
  url: https://github.com/psychemedia/storynotes
  path_to_book: .
  branch: main

html:
  use_repository_button: true

launch_buttons:
  notebook_interface: jupyterlab
  thebe: true
  binderhub_url: https://mybinder.org
  retrolite_url: ./lite/retro/notebooks/

execute:
  execute_notebooks: cache
  timeout: 60  
parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    html_copy_source: false
    html_theme: sphinx_book_theme

  extra_extensions:
    - jupyterlite_sphinx
    - sphinx_togglebutton
